### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/corepc#1]
Hey @apoelstra can you give me maintainer permissions on this repo please.

I tried transfering and now it doesn't like it because the repo exists already. I'm thinking I'll just:

- Push the state I've got locally to master
- Push all tags (includes tags for the `bitcoind-json-rpc-*` releases and `corepct-*` releases
- Check I've got everything correct by doing a trivial PR to run through CI
- Finish the testing I want to do before next release
- Release `0.5.0` (includes most of the RPC methods on v17 and hopefully v18)
- Take a breather

**Comment by apoelstra** [comment]
Done. You should be admin now.

**Comment by tcharding** [comment]
We can close this now. I force pushed to master - YOLO.
