### ISSUE TITLE
Repository link on `crates.io` references fork incorrectly

### ISSUE THREAD

**Issue by AaronFeickert** [rust-bitcoin/corepc#16]
The repository link for the `corepc-node` [crate](https://crates.io/crates/corepc-node) attempts to link to a [fork](https://github.com/tcharding/corepc) instead of this repository. However, even that link is [broken](https://github.com/tcharding/corepc/corepc-node).

**Comment by AaronFeickert** [comment]
See #17 for a related issue.

**Comment by tcharding** [comment]
This is fixed on master and will be release in as part of 0.5.0 in #23 

Thanks for raising the issue!
