### ISSUE TITLE
Feature request for `invalidateblock` RPC

### ISSUE THREAD

**Issue by rustaceanrob** [rust-bitcoin/corepc#19]
A somewhat hidden but useful command for development is the `invalidate_block` call that instructs `bitcoind` to treat a block as if it violates consensus. In combination with `generate_to_address` this may be used to simulate chain reorganizations on Regtest. It does not actually come up when calling `bitcoin-cli help`, but it was present within `bitcoincore-rpc` [here](https://docs.rs/bitcoincore-rpc/latest/src/bitcoincore_rpc/client.rs.html#921-923). I tried taking a stab at adding the macro to `v17` but I got lost as to how to implement it for each subsequent version, and I am also unsure what section it should go under. 

Maybe I am missing a different command that would reorganize blocks, any insight on that front is welcome.

ref: https://github.com/bitcoin/bitcoin/blob/ff873a20a7f48698da3334acc570d97a07016ddf/src/rpc/blockchain.cpp#L1619

**Comment by tcharding** [comment]
If a method does not return anything then we don't need explicit support for it. Eg one can just call it like this `self.call("invalidateblock", &[])`

**Comment by rustaceanrob** [comment]
Gotcha. Could the `corepc-node` crate potentially export `serde_json`? I am finding that I need it for the `Value` type. This might already be possible without the export and I am a dullard after my short leave

**Comment by tcharding** [comment]
I see no reason not to. If we are going to do it we might as well do all the deps

```
log = "0.4"
which = "4.2.5"
anyhow = "1.0.66"
tempfile = "3"
serde_json = { version = "1.0.117" }
```
