### ISSUE TITLE
Are the derives on model types correct

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/corepc#2]
I can't remember why I used the current set of derives e.g,

```rust
/// Models the result of JSON-RPC method `getbestblockhash`.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct GetBestBlockHash(pub BlockHash);
```

And 

```rust
/// Models the result of JSON-RPC method `getblock` with verbosity set to 0.
#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
pub struct GetBlockVerbosityZero(pub Block);
```

Why no `Ord`/`PartialOrd`, is `Eq` correct?

**Comment by apoelstra** [comment]
We probably want `Eq` and `PartialEq` for tests, if nothing else. I think every RPC call returns structured data that has a sensible notion of equality.

Ordering/Hash is basically in case people want to put the types into a BTreeSet or something. But I don't think these types are intended to be stored, just to be immediately converted into something application-specific right?

**Comment by tcharding** [comment]
I just remembered that the API guidelines say that data structures should eagerly implement these. I agree with your reasoning but I rekon we should throw them on.

**Comment by apoelstra** [comment]
While the API guidelines say we should eagerly impl them, Kix has argued elsewhere that it's potentially dangerous or confusing for types where there isn't a single obvious natural ordering.

Now, for these types, there is obviously no "natural ordering" that somebody would depend on; the types have no consensus meaning and live in no well-defined protocol; etc. So it's hard for me to imagine `Ord` causing anyone problems.

But I (weakly) vote that we leave them off for now and wait for somebody to file a bug.

**Comment by tcharding** [comment]
Aight, that's good enough for me. I wasn't planning on 1.0-ing this caret anytime soon anyways. Thanks man.
