### ISSUE TITLE
Run the formatter in CI

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/corepc#20]
This requires contributors to have access to `nightly`, I'm happy to run the formatter for you want to contribute and you do not have nightly.

**Comment by apoelstra** [comment]
I'd be fine requiring formatting here. If people complain I'd also be fine copying the rust-bitcoin "the bot does it once a week" scheme.

**Comment by tcharding** [comment]
I loath the formatting bot method but put up with it because of other people, we don't have that  problem in this repo.
